import turtle

jack = turtle.Turtle()
scn = turtle.Screen()
con = turtle.Turtle()
ninja = turtle.Turtle()
joe = turtle.Turtle()
tom = turtle.Turtle()
j = turtle.Turtle()
bob = turtle.Turtle()
turtle.speed(100)

jack.shape("classic")
con.shape("classic")
ninja.shape("classic")
joe.shape("classic")

con.penup()
con.color("green")
con.goto(-400, 0)
con.pendown()
con.begin_fill()
con.forward(800)
con.right(90)
con.forward(500)
con.right(90)
con.forward(800)
con.right(90)
con.forward(500)
con.end_fill()

joe.penup()
joe.goto(-400, 0)
joe.pendown()
joe.begin_fill()
joe.forward(800)
joe.left(90)
joe.forward(600)
joe.left(90)
joe.forward(800)
joe.left(90)
joe.forward(600)
joe.end_fill()

tom.penup()
tom.color("white")
tom.goto(200, 300)
tom.begin_fill()
tom.circle(75)
tom.end_fill()

jack.penup()
jack.color("red")
jack.goto(-300, -20)
jack.pendown()
jack.begin_fill()
jack.forward(150)
jack.left(90)
jack.forward(150)
jack.left(90)
jack.forward(150)
jack.left(90)
jack.forward(150)
jack.end_fill()

ninja.penup()
ninja.color("blue")
ninja.goto(-300, 130)
ninja.left(60)
ninja.pendown()
ninja.begin_fill()
ninja.forward(150)
ninja.right(120)
ninja.forward(150)
ninja.right(120)
ninja.forward(150)
ninja.end_fill()

j.penup()
j.color("yellow")
j.goto(-230, -20)
j.pendown()
j.begin_fill()
j.forward(30)
j.left(90)
j.forward(50)
j.left(90)
j.forward(30)
j.left(90)
j.forward(50)
j.end_fill()

bob.penup()
bob.goto(-275, 70)
bob.color("light yellow")
bob.begin_fill()
bob.forward(30)
bob.left(90)
bob.forward(30)
bob.left(90)
bob.forward(30)
bob.left(90)
bob.forward(30)
bob.left(90)
bob.end_fill()
bob.penup()
bob.forward(70)
bob.begin_fill()
bob.forward(30)
bob.left(90)
bob.forward(30)
bob.left(90)
bob.forward(30)
bob.left(90)
bob.forward(30)
bob.left(90)
bob.end_fill()

joe.penup()
joe.goto(-260, 70)
joe.pendown()
joe.left(180)
joe.forward(30)
joe.penup()
joe.goto(-275, 85)
joe.right(90)
joe.pendown()
joe.forward(30)
joe.penup()
joe.goto(-190, 70)
joe.pendown()
joe.left(90)
joe.forward(30)
joe.penup()
joe.goto(-205, 85)
joe.right(90)
joe.pendown()
joe.forward(30)





scn.exitonclick()


